#!/bin/bash

n
+1G

n
+1G

n
+1G


n
e


n
+1G

n
+1G

n
+1G

n
+1G

n
+1G

n
+1G

n

p


w

sudo fdisk /dev/sdd -l

sudo mkfs.ext4 /dev/sdd1
sudo mkfs.ext4 /dev/sdd2
sudo mkfs.ext4 /dev/sdd3
sudo mkfs.ext4 /dev/sdd5
sudo mkfs.ext4 /dev/sdd6
sudo mkfs.ext4 /dev/sdd7
sudo mkfs.ext4 /dev/sdd8
sudo mkfs.ext4 /dev/sdd9
sudo mkfs.ext4 /dev/sdd10
sudo mkfs.ext4 /dev/sdd11

sudo vim /etc/fstab

LABEL=cloudimg-rootfs   /        ext4   discard,errors=remount-ro       0 1
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
home_vagrant_foo /home/vagrant/foo vboxsf uid=1000,gid=1000,_netdev 0 0
#VAGRANT-END

/dev/sdd1       /Examenes-UTN/alumno_1/parcial_1  ext4    defaults      0 2
/dev/sdd2       /Examenes-UTN/alumno_1/parcial_2  ext4    defaults      0 2
/dev/sdd3       /Examenes-UTN/alumno_1/parcial_3  ext4    defaults      0 2
/dev/sdd5       /Examenes-UTN/alumno_2/parcial_1  ext4    defaults      0 2
/dev/sdd6       /Examenes-UTN/alumno_2/parcial_2  ext4    defaults      0 2
/dev/sdd7       /Examenes-UTN/alumno_2/parcial_3  ext4    defaults      0 2
/dev/sdd8       /Examenes-UTN/alumno_3/parcial_1  ext4    defaults      0 2
/dev/sdd9       /Examenes-UTN/alumno_3/parcial_2  ext4    defaults      0 2
/dev/sdd10      /Examenes-UTN/alumno_3/parcial_3  ext4    defaults      0 2
/dev/sdd11      /Examenes-UTN/profesores          ext4    defaults      0 2


sudo mount -a

sudo lsblk

